# Logging configuration
logLevel: "debug"  # Options: debug, info, warning, error

# Container configuration
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 512Mi

image:
  ecrRegistry: "028374682934"
  tag: latest

# Health checks
livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/ready
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 5
startupProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 45
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 6

# Security Context
podSecurityContext:
  fsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1001
  readOnlyRootFilesystem: true
