apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugger-sa
  labels:
    {{- include "dallas-debugger.labels" . | nindent 4 }}
{{- if ne .Values.cloudProvider "aws" }}
imagePullSecrets:
  - name: ecr-cred
{{- end }}
